version: '3.0'
# execute `docker compose up` in terminal

services:
  composer:
    image: composer
    command: update
    volumes:
      - ./wordpress:/app

  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: madwell
      MYSQL_USER: madwell
      MYSQL_PASSWORD: madwell
    volumes:
      -  ./mysql:/var/lib/mysql

  phpmyadmin:
    ### go to localhost:8181, then import db sql file (e.g. madwell.sql) file from team/dev/prod

    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8181:80

  wordpress: # credentials: madwell / madwell
    ### go to localhost:8888/wp-admin

    ### choose "Twenty Twenty-One" theme for multiple menus

    ### set Menu locations: Primary -> Header, Secondary -> Footer

    ### save Permalinks setting in Settings, preferably "Post name"

    ### install plugins (listed in `/wordpress/composer.json` file)
    ## use `composer update` or, in case that doesn't work, install them manually

    ### how to update upload_max_filesize (when uploading zip file is too big)
    ## via editing `.htaccess` file: add lines below to the top or bottom
    # php_value upload_max_filesize 256M
    ## or ##
    ## via terminal (find docker container id by `docker ps`, then below...): 
    # docker container exec -it [CONTAINER ID] bash -c "echo 'php_value upload_max_filesize 256M' > '/var/www/html/.htaccess'"

    ### copy & paste `/wp-content/uploads` folder from team/dev/prod

    depends_on:
      - mysql
      - composer
    image: wordpress:latest
    ports:
      - "8888:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: madwell
      WORDPRESS_DB_PASSWORD: madwell
      WORDPRESS_DB_NAME: madwell
    volumes:
      - ./wordpress:/var/www/html

volumes:
  mysql_data: {}

  
