version: '3.0'

services:
  composer:
    image: composer
    command: update
    volumes:
      - ./wordpress:/app

  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: madwell
      MYSQL_USER: madwell
      MYSQL_PASSWORD: madwell
    volumes:
      -  ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8181:80

  wordpress:
    depends_on:
      - mysql
      - composer
    image: wordpress:latest
    ports:
      - "8888:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: madwell
      WORDPRESS_DB_PASSWORD: madwell
      WORDPRESS_DB_NAME: madwell
    volumes:
      - ./wordpress:/var/www/html

volumes:
  mysql_data: {}

  
